### ISSUE TITLE
Fish bp is belize

### ISSUE THREAD

**Issue by EOSMediterranean** [eosmedi/votetracker-front#11]
![screen shot 2018-10-14 at 18 39 10](https://user-images.githubusercontent.com/39888664/46919503-8ec99680-cfe0-11e8-9d5a-5522a096e275.png)
Country is Belize

**Comment by lljxx1** [comment]
yes， that is correct

**Comment by EOSMediterranean** [comment]
> yes， that is correct

But still the same.....it does not say Belize as country it says BPFish
