### ISSUE TITLE
Eos Nairobi country is Kenya

### ISSUE THREAD

**Issue by EOSMediterranean** [eosmedi/votetracker-front#22]
![screen shot 2018-10-15 at 14 09 09](https://user-images.githubusercontent.com/39888664/46950137-069ccd00-d084-11e8-9c3f-d460d8f064d8.png)

It says East Africa, you can put Nairobi or Kenya

**Comment by lljxx1** [comment]
don't put this kind of issue again 
they set up as KE, every flag are follow their config

 "location":{
         "name":"EastAfrica",
         "country":"KE",
         "latitude":0.0236,
         "longitude":37.9062
      },
