### ISSUE TITLE
Flag and country/city should be on same line

### ISSUE THREAD

**Issue by EOSMediterranean** [eosmedi/votetracker-front#23]
Sometimes, flag and city/country is on the same line(beijing,Fish,Tokyo)
Sometimes it fall bellow(Chengdu,Shanghai)
All should be better on the same line
Also, sometimes we are using country name, sometimes city name, we should decide one of the two

![screen shot 2018-10-15 at 17 43 53](https://user-images.githubusercontent.com/39888664/46961890-10cdc400-d0a2-11e8-8010-56d88e7915b8.png)

**Comment by lljxx1** [comment]
use flag country name
