### ISSUE TITLE
Accordion in History/Search

### ISSUE THREAD

**Issue by EOSMediterranean** [eosmedi/votetracker-front#33]
only first action you can close in the history/search part ,

![screen shot 2018-10-16 at 23 46 53](https://user-images.githubusercontent.com/39888664/47050151-9c794a80-d19f-11e8-9a65-dd98c002d7b1.png)

if you try to close second one it opens first one, 

![screen shot 2018-10-17 at 00 03 39](https://user-images.githubusercontent.com/39888664/47050396-8029dd80-d1a0-11e8-8019-2aad15d78ca3.png)

it is importamt to be able tp close one by one, as many people will search info from various BP at the same time to compare

**Comment by lljxx1** [comment]
ok
