### ISSUE TITLE
Choose one of the two ways to register proxy?

### ISSUE THREAD

**Issue by EOSMediterranean** [eosmedi/votetracker-front#6]
![screen shot 2018-10-13 at 20 41 05](https://user-images.githubusercontent.com/39888664/46908793-76964080-cf28-11e8-8f2b-f320d2dac266.png)
This could be confusing,two ways to do the same thing?
Maybe best to use this only?
![screen shot 2018-10-13 at 20 43 06](https://user-images.githubusercontent.com/39888664/46908808-9fb6d100-cf28-11e8-8714-c30af71c6c20.png)

**Comment by lljxx1** [comment]
OK
