### ISSUE TITLE
Proxy table 

### ISSUE THREAD

**Issue by EOSMediterranean** [eosmedi/votetracker-front#7]
![screen shot 2018-10-14 at 13 16 07](https://user-images.githubusercontent.com/39888664/46915934-7b540680-cfb3-11e8-80f8-ca4605da6d7d.png)

Last 3 items in Proxy table don't work well:

Location: almost not used
WWW: many links don't work(send you back to main producer list)bad ux
Chat button: to big, off centered

Those 3 items are not needed since we have all that info inside each proxy, maybe better take those items off from the front page?

**Comment by lljxx1** [comment]
stay the chat button ，notice new feature
